### ISSUE TITLE
Is each sample point seeded with two gaussians? 

### ISSUE THREAD

**Issue by DeepDuke** [VladimirYugay/Gaussian-SLAM#24]
![image](https://github.com/VladimirYugay/Gaussian-SLAM/assets/15854511/8f95e9cf-ad0c-4012-b85d-e77223c7f01c)
 
Thanks for your great work! I have two questions.

In the section of **Building Sub-maps Progressively**,  it's said 

> For each sampled point, we seed two gaussians

Where is the corresponding code ?  I only saw one gaussian is seeded. 

BTW, what does `features_dc` and `features_rest` mean in gaussian model? TKS!

**Comment by VladimirYugay** [comment]
Hey there,

Thanks for your interest in our work. The code we released is slightly different from the paper on arxiv. 

1. Arxiv is a little bit outdated. In the current implementation, we seed only 1 Gaussian - as you said
2. Features dc and rest relate to the spherical harmonics used to describe the color. We don't go into the details in the paper since it's well described in the original Gaussian splatting paper. For example, this Github [issue](https://github.com/graphdeco-inria/gaussian-splatting/issues/728) answers your exact question.
